### ISSUE TITLE
zigbee-herdsman converter for Zigbee sample to work out-of-the-box in Zigbee2MQTT and IoBroker

### ISSUE THREAD

**Issue by Hedda** [rbaron/b-parasite#90] opened 2022-12-27 12:09 UTC
zigbee-herdsman converter for sample based b-parasite Zigbee devices to work out-of-the-box in Zigbee2MQTT and IoBroker:

https://github.com/rbaron/b-parasite/tree/main/code/nrf-connect/samples/zigbee

As per the initial Zigbee sample pull request:

https://github.com/rbaron/b-parasite/pull/81

https://github.com/rbaron/b-parasite/tree/main/code/nrf-connect/samples/zigbee

> The `b-parasite.js` file in this PR contains a converter that can be installed to Zigbee2MQTT to support this sample. See "Support new devices" for instructions.

https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

Will anyone submit that `b-parasite.js` converter file as a pull request to zigbee-herdsman-converters repo for inclusion by default?

https://github.com/Koenkk/zigbee-herdsman-converters

**Comment by ginkel** [comment] 2023-05-27 23:19
If that's ok for @rbaron, I can submit a PR to [zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters).

**Comment by rbaron** [comment] 2023-05-28 07:37
Thanks @ginkel, that would be great. Could you please test [our converter](https://github.com/rbaron/b-parasite/blob/main/code/nrf-connect/samples/zigbee/b-parasite.js) against the latest HA just to be sure before submitting it? We also need to [submit a photo](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_4-add-device-picture-to-zigbee2mqtt-io-documentation). I would suggest [this one](https://github.com/rbaron/b-parasite/blob/main/img/resized/b-parasite-2.0.0.jpg).

Thanks!

**Comment by ginkel** [comment] 2023-05-28 09:45
Excellent! I am using the b-parasite with z2m and latest HA 2023.5.4, so I can confirm that everything is working as expected. I just noticed in the converter that battery voltage reporting is commented out. Do you remember the reason for this?

Regarding the photo: I do have one with a more neutral background. The PCB has slightly rounded edges, though, but is unmodified otherwise: https://photos.app.goo.gl/smRuBSAahcgkgPyx8

**Comment by rbaron** [comment] 2023-05-28 10:04
> Do you remember the reason for this?

IIRC I thought the `batteryVoltage` attribute was not reportable, only the percentage. But I see [some devices in the converts repo](https://github.com/search?q=repo%3AKoenkk%2Fzigbee-herdsman-converters%20batteryVoltage&type=code) that do configure it for reporting, so maybe I was wrong 😬. It would be great to give this a test, but we can also remove the commented code and just work with the percentage for now. Up to you! 

> Regarding the photo

I kinda like the one in our repo because it gives a sense of scale with the coin and also shows the battery clip on the back. Unless you feel strongly about it, I'd vote for that one.

Tks again!

**Comment by rbaron** [comment] 2023-05-28 10:10
@ginkel I think I remember the reason now. In the [Zigbee Cluster Library specs](https://zigbeealliance.org/wp-content/uploads/2019/12/07-5123-06-zigbee-cluster-library-specification.pdf) (section 3.3.2.2.3):

<img width="595" alt="image" src="https://github.com/rbaron/b-parasite/assets/1573409/71c83c63-91e9-48ce-888e-3d70ae67f018">

Only the `BatteryPercentageRemaining` is marked as reportable, and `BatteryVoltage` is not. But it's possible that different stacks also handle reporting on it.

**Comment by ginkel** [comment] 2023-05-28 10:11
Interesting. I have a couple of ZigBee devices that report the battery voltage, so I'll see if I can get this working.

**Comment by ginkel** [comment] 2023-05-28 19:28
> I kinda like the one in our repo because it gives a sense of scale with the coin and also shows the battery clip on the back. Unless you feel strongly about it, I'd vote for that one.

I think we need a photo with a white background, at least that's what is usually requested when adding a new device.

**Comment by rbaron** [comment] 2023-05-28 20:14
@ginkel Sounds good, if that's a requirement please feel free to use the one you took. Thanks for pushing this forward.

**Comment by ginkel** [comment] 2023-05-30 12:09
The [PR](https://github.com/Koenkk/zigbee-herdsman-converters/pull/5810) has been merged, I expect the support to be part of the next zigbee2mqtt release.

**Comment by rbaron** [comment] 2023-05-30 18:38
That's great, thanks once again @ginkel.

**Closed by rbaron** 2023-05-30 18:38 UTC
